#spring.application.name=olist-service
server.port=9091
#path from environment or default
jwt.publicKeyPath=${JWT_PUBLIC_KEY_PATH:./config/keys/public.pem}

# allow url
requests.public-urls[0]=/authen
requests.public-urls[1]=/olist/healthcheck

logging.file.name=logs/history-logging-olist-service.log
logging.level.root=INFO
logging.level.com.ana=DEBUG
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger - %msg%n


## Cookie config
jwt.cookie.refreshTokenName=refreshToken
jwt.cookie.accessTokenName=accessToken
jwt.cookie.path=/
jwt.cookie.http-only=true
jwt.cookie.secure=false
jwt.cookie.same-site=Lax
jwt.cookie.max-age=604800



spring.datasource.url=${PG_DATABASE_URI}
spring.datasource.username=${PG_DATABASE_USER_NAME}
spring.datasource.password=${PG_DATABASE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true